# Generated by Django 4.2.3 on 2023-07-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
