# Generated by Django 4.2.3 on 2023-07-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MusicApp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(max_length=100)),
            ],
        ),
    ]
