# Generated by Django 4.2.3 on 2023-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='user',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
